# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [5]:
# Create a 1-dimensional NumPy array using np.array()
a = np.array([1,2,3])
print(a)

# Create a 2-dimensional NumPy array using np.array()
b = np.array([[1,2],[1,2]])
print(b)
# Create a 3-dimensional Numpy array using np.array()

c = np.array([[[1,2],[1,2]],[[1,2],[1,2]]])
c

[1 2 3]
[[1 2]
 [1 2]]


array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
for i in (a,b,c):
    print(i.dtype, i.size, i.ndim, type(i))

int64 3 1 <class 'numpy.ndarray'>
int64 4 2 <class 'numpy.ndarray'>
int64 8 3 <class 'numpy.ndarray'>


In [14]:
# Attributes of 2-dimensional array
b.shape, b.itemsize, b.ndim, b.dtype

((2, 2), 8, 2, dtype('int64'))

In [18]:
# Attributes of 3-dimensional array
c.shape, c.itemsize, c.ndim, c.dtype

((2, 2, 2), 8, 3, dtype('int64'))

In [19]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,size=(7,2))

array([[4, 3],
       [9, 2],
       [1, 7],
       [3, 1],
       [6, 0],
       [6, 6],
       [1, 7]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)

array([[3.18683845e-01, 8.46859789e-01, 7.05789473e-01, 2.27653102e-01,
        9.80617913e-01],
       [3.82181008e-01, 7.91111755e-01, 3.68190223e-01, 8.33307012e-01,
        5.54861692e-01],
       [7.67552782e-01, 6.88236016e-01, 9.85218801e-02, 9.65002362e-04,
        1.69241300e-01]])

In [10]:
import numpy as np
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10, size = (4,6))



array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [3]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

a = np.random.randint(1,10,size=(3,7))
print(a)

# Find the unique numbers in the array you just created
np.unique(a)


[[1 1 5 8 1 9 7]
 [2 5 7 8 2 7 2]
 [7 5 1 2 7 3 5]]


array([1, 2, 3, 5, 7, 8, 9])

In [15]:
np.unique(a,return_index=True)

(array([1, 2, 3, 5, 6, 7, 8, 9]), array([ 5,  4, 10,  9, 12,  1,  3,  0]))

In [4]:
np.unique(a,return_inverse=True)

(array([1, 2, 3, 5, 7, 8, 9]),
 array([0, 0, 3, 5, 0, 6, 4, 1, 3, 4, 5, 1, 4, 1, 4, 3, 0, 1, 4, 2, 3]))

In [6]:
np.unique(a,return_inverse=True)[1].size

21

In [17]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 5, 6, 7, 8, 9]), array([3, 1, 4, 3, 1, 4, 3, 2]))

In [18]:
# Find the 0'th index of the latest array you created
a[0]

array([9, 7, 9, 8, 2, 1, 7])

In [19]:
# Get the first 2 rows of latest array you created
a[0:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [26]:
# Get the first 2 values of the first 2 rows of the latest array
print(a)
a[0:2,0:2]

[[9 7 9 8 2 1 7]
 [7 8 5 3 8 6 3]
 [1 3 5 3 1 5 7]]


array([[9, 7],
       [7, 8]])

In [29]:
# Create a random array of numbers between 0 & 10 and an array of ones
arr1 = np.random.randint(1,10,size=(3,5))
arr2 = np.ones((3,5))
# both of size (3, 5), save them both to variables
arr1,arr2


(array([[9, 5, 6, 4, 7],
        [9, 7, 1, 1, 9],
        [9, 4, 9, 3, 7]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [30]:
# Add the two arrays together
arr1+arr2

array([[10.,  6.,  7.,  5.,  8.],
       [10.,  8.,  2.,  2., 10.],
       [10.,  5., 10.,  4.,  8.]])

In [31]:
# Create another array of ones of shape (5, 3)
arr3 = np.ones((5,3))

In [32]:
# Try add the array of ones and the other most recent array together
arr2 + arr3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [33]:
# Create another array of ones of shape (3, 5)
arr_ones = np.ones((3,5))

In [35]:
# Subtract the new array of ones from the other most recent array
arr1 - arr_ones

array([[8., 4., 5., 3., 6.],
       [8., 6., 0., 0., 8.],
       [8., 3., 8., 2., 6.]])

In [36]:
# Multiply the ones array with the latest array
arr1 * arr_ones

array([[9., 5., 6., 4., 7.],
       [9., 7., 1., 1., 9.],
       [9., 4., 9., 3., 7.]])

In [37]:
# Take the latest array to the power of 2 using '**'
arr1**2

array([[81, 25, 36, 16, 49],
       [81, 49,  1,  1, 81],
       [81, 16, 81,  9, 49]])

In [38]:
# Do the same thing with np.square()
np.square(arr1)

array([[81, 25, 36, 16, 49],
       [81, 49,  1,  1, 81],
       [81, 16, 81,  9, 49]])

In [39]:
# Find the mean of the latest array using np.mean()
np.mean(arr1)

6.0

In [40]:
# Find the maximum of the latest array using np.max()
np.max(arr1)

9

In [41]:
# Find the minimum of the latest array using np.min()
np.min(arr1)

1

In [42]:
# Find the standard deviation of the latest array
np.std(arr1)

2.780887148615228

In [44]:
# Find the variance of the latest array
variance = np.std(arr1)**2
variance

7.733333333333333

In [45]:
# Reshape the latest array to (3, 5, 1)
arr1.reshape(3,5,1)

array([[[9],
        [5],
        [6],
        [4],
        [7]],

       [[9],
        [7],
        [1],
        [1],
        [9]],

       [[9],
        [4],
        [9],
        [3],
        [7]]])

In [46]:
# Transpose the latest array
arr1.transpose()

array([[9, 9, 9],
       [5, 7, 4],
       [6, 1, 9],
       [4, 1, 3],
       [7, 9, 7]])

What does the transpose do?

In [48]:
# Create two arrays of random integers between 0 to 10
a1 = np.random.randint(0,10,size=(3,3))
a2 = np.random.randint(0,10,size=(3,2))
a1,a2
# one of size (3, 3) the other of size (3, 2)


(array([[3, 6, 1],
        [2, 0, 4],
        [0, 7, 0]]),
 array([[0, 1],
        [1, 5],
        [6, 4]]))

In [50]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

array([[12, 37],
       [24, 18],
       [ 7, 35]])

In [51]:
# Create two arrays of random integers between 0 to 10
a1 = np.random.randint(0,10,size=(4,3))
a2 = np.random.randint(0,10,size=(4,3))
a1,a2
# both of size (4, 3)


(array([[0, 0, 2],
        [1, 4, 9],
        [5, 6, 3],
        [6, 7, 0]]),
 array([[5, 7, 4],
        [3, 1, 5],
        [5, 0, 8],
        [5, 2, 3]]))

In [52]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [53]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a1.transpose(),a2)

array([[58, 13, 63],
       [77, 18, 89],
       [52, 23, 77]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
# already done


In [54]:
# Compare the two arrays with '>'
a1 > a2

array([[False, False, False],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [55]:
# Compare the two arrays with '>='
a1 >= a2

array([[False, False, False],
       [False,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [58]:
# Find which elements of the first array are greater than 7
print(a1)
a1[a1>7]

[[0 0 2]
 [1 4 9]
 [5 6 3]
 [6 7 0]]


array([9])

In [59]:
# Which parts of each array are equal? (try using '==')
a1 == a2

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False]])

In [62]:
# Sort one of the arrays you just created in ascending order
print(a1)
np.sort(a1)

[[0 0 2]
 [1 4 9]
 [5 6 3]
 [6 7 0]]


array([[0, 0, 2],
       [1, 4, 9],
       [3, 5, 6],
       [0, 6, 7]])

In [63]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [2, 0, 1]])

In [65]:
# Find the index with the maximum value in one of the arrays you've created
a1,np.argmax(a1)

(array([[0, 0, 2],
        [1, 4, 9],
        [5, 6, 3],
        [6, 7, 0]]),
 5)

In [66]:
# Find the index with the minimum value in one of the arrays you've created
a2,np.argmin(a2)

(array([[5, 7, 4],
        [3, 1, 5],
        [5, 0, 8],
        [5, 2, 3]]),
 7)

In [69]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
a2,np.argmax(a2,axis=1),np.max(a2,axis=1)

(array([[5, 7, 4],
        [3, 1, 5],
        [5, 0, 8],
        [5, 2, 3]]),
 array([1, 2, 2, 0]),
 array([7, 5, 8, 5]))

In [72]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
a2,np.argmin(a2,axis=0),np.min(a2,axis=0)

(array([[5, 7, 4],
        [3, 1, 5],
        [5, 0, 8],
        [5, 2, 3]]),
 array([1, 2, 3]),
 array([3, 0, 3]))

In [76]:
# Create an array of normally distributed random numbers
np.random.randn(5,5)

array([[-1.0967523 , -0.68230156,  0.88751161,  0.60548313, -0.72029799],
       [-0.26993377, -0.14346223,  0.61700378,  1.2489407 ,  0.06564916],
       [ 1.16920765,  0.87331697,  0.20565013, -1.44348335, -1.02771086],
       [ 0.74124064, -1.71052958,  0.11897849,  1.00048561,  0.15242086],
       [-0.60139725, -0.84661436,  0.81615272,  0.47170729, -0.2854893 ]])

In [77]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.