In [4]:
import numpy as np


In [2]:
# 0d array means only one element
np.array(100)

array(100)

In [3]:
# 1d array means array of 0d elements
np.array([1,2,3])

array([1, 2, 3])

In [4]:
# 2d array means array of 1d arrays
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 3d array means array of 2d arrays
threed = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
threed

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
# general defn of row: the elements of the outermost array are called rows []
# general defn of col: go one level deep ie [[ ]] the first element of all items at that depth constitutes cols

In [10]:
threed.sum(axis = 0) # col wise

array([[ 8, 10, 12],
       [14, 16, 18]])

In [11]:
threed.sum(axis = 1) # row wise

array([[ 5,  7,  9],
       [17, 19, 21]])

In [12]:
# dimension = level of depth of array
threed.ndim

3

In [13]:
type(threed)

numpy.ndarray

In [2]:
# creating arrays with existing data
# np.asarray(input, dtype, order)
# order => row major = "C", col major = "F"
# by default its row major order

In [7]:
mylist = [10,20,30]
np.asarray(mylist)

array([10, 20, 30])

In [11]:
my_new_list = [[10,20,30], [40,50,60]]
np.asarray(my_new_list)

array([[10, 20, 30],
       [40, 50, 60]])

In [37]:
# np.nditer() # efficient multi dim iterator object to iterate over arrays
rm = np.asarray(my_new_list) # row major order
cm = np.asarray(my_new_list,order="F") # col major order
print("rm", rm)
print("cm",cm)
# we dont observe any difference when we print them

print("row major storage")
for i in np.nditer(rm):
    print(i,end=" ")
print("\n col major storage")
for i in np.nditer(cm):
    print(i,end=" ")

rm [[10 20 30]
 [40 50 60]]
cm [[10 20 30]
 [40 50 60]]
row major storage
10 20 30 40 50 60 
 col major storage
10 40 20 50 30 60 

In [17]:
# np.frombuffer(buffer,dtype,count, offset)
# count restricts the length of the data
# offset is the position from where we require the data
s = b"Welcome" # byte string
np.frombuffer(s,dtype="S1", count = -1, offset = 0)
# default count -1 => complete data
# default offset 0 => starting position

# S1 and S2 are string data type descriptors. the first means that the array holds strings of length 1, the second of length 2
# remember to write S in caps

array([b'W', b'e', b'l', b'c', b'o', b'm', b'e'], dtype='|S1')

In [18]:
np.frombuffer(s,dtype="S1", count=3, offset=2)

array([b'l', b'c', b'o'], dtype='|S1')

In [21]:
np.frombuffer(s,dtype="S2")

ValueError: buffer size must be a multiple of element size

In [22]:
np.frombuffer(s,dtype="S2", offset=1)

array([b'el', b'co', b'me'], dtype='|S2')

In [23]:
np.frombuffer(s,dtype="S2",count=2)

array([b'We', b'lc'], dtype='|S2')

In [25]:
np.frombuffer(s,dtype="S3",count=1)

array([b'Wel'], dtype='|S3')

In [29]:
# np.fromiter(iterable,dtype,count)
np.fromiter(range(100))

TypeError: fromiter() missing required argument 'dtype' (pos 2)

In [30]:
np.fromiter(range(100), dtype=int)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
np.fromiter("123456789",dtype=float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# arrays with numerical ranges arange, linspace, logspace
# all these functions will return me an array with values in given range, and required datatype