# Assignment on NumPy

In [282]:
!pip install numpy
import numpy as np


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip


# Question 1

1a) Create a 1D-array like the following without hardcoding.

Input:
```
arr = np.array([1,2,3])

output
A = array([1, 1, 1, 2, 2, 2, 3, 3, 3])



In [283]:
arr = np.array([[i]*3 for i in range(1,4)]).reshape((9))
arr

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

1b) Create the following array B without hardcoding and find the common values in A (Array created in 2a) and B

Input:
```
arr = np.array([1,2,3])

B = array([1, 2, 3, 1, 2, 3, 1, 2, 3])

output
array([1, 2, 3])



In [284]:
arr2 = np.array([[1,2,3]*3])
arr2

array([[1, 2, 3, 1, 2, 3, 1, 2, 3]])

1c) Get the locations of the elements where they match.

In [285]:
arr == arr2

array([[ True, False, False, False,  True, False, False, False,  True]])

In [286]:
np.equal(arr,arr2)

array([[ True, False, False, False,  True, False, False, False,  True]])

# Question 2

2a) Create a random 2D array with float values between 5 and 20.

In [287]:
np.random.seed(123321) # to make my results re-producible
ran_arr = np.random.uniform(low=5, high=20, size=(3,3))
ran_arr


array([[ 9.51006997,  5.60558459,  9.35914917],
       [17.07333374, 10.20600126, 14.60473832],
       [16.0643647 ,  6.75830634, 13.9009962 ]])

2b) Print the array with only 2 decimal values

In [288]:
print(np.array_str(ran_arr,precision=2))

[[ 9.51  5.61  9.36]
 [17.07 10.21 14.6 ]
 [16.06  6.76 13.9 ]]


2c) Normalize the values between 0 and 1

In [289]:
normalized = ran_arr/np.linalg.norm(ran_arr)
normalized

array([[0.262214  , 0.15455856, 0.25805277],
       [0.47075017, 0.28140239, 0.40268545],
       [0.44293063, 0.18634169, 0.3832817 ]])

2d) Find the maximum value in each row and minimum value in each column

In [290]:
ran_arr.max(axis=1) # maximum values in each row

array([ 9.51006997, 17.07333374, 16.0643647 ])

In [291]:
ran_arr.min(axis=0) #minimum values in each col

array([9.51006997, 5.60558459, 9.35914917])

# Question 3

3a) Load the heights of US president dataset. (https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/master/notebooks/data/president_heights.csv)

In [292]:
url = "https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/master/notebooks/data/president_heights.csv"
import pandas as pd
us_pres_df = pd.read_csv(url)
us_pres_df
# used pandas for convinience as there is no constraint mentioned explicitly

order                    name  height(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
21     23       Benjamin Harrison         168
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

3b) Find is there any null value using numpy.

In [293]:
for col in us_pres_df.columns:
    if us_pres_df[col].dtype != "object":
        print(f"checking nan in {col}")
        print(us_pres_df[np.isnan(us_pres_df[col])])

# numpy can only deal with numeric cols


checking nan in order
Empty DataFrame
Columns: [order, name, height(cm)]
Index: []
checking nan in height(cm)
Empty DataFrame
Columns: [order, name, height(cm)]
Index: []


3c) Find is there any null value using numpy.

In [294]:
us_pres_df.isnull().sum()

order         0
name          0
height(cm)    0
dtype: int64

3d) Find the top two presidents with max height and min height.

In [295]:
max_ht, min_ht = us_pres_df["height(cm)"].max(), us_pres_df["height(cm)"].min()

us_pres_df[ us_pres_df["height(cm)"] ==  max_ht]

order               name  height(cm)
15     16    Abraham Lincoln         193
33     36  Lyndon B. Johnson         193

In [296]:
us_pres_df[ us_pres_df["height(cm)"] ==  min_ht]


order           name  height(cm)
3      4  James Madison         163

3e) Find the most frequent height and display the names of the presidents whose height is greater than the frequent height.

In [297]:
ht_mode = us_pres_df["height(cm)"].mode().values[0]
ht_mode

183

In [298]:
us_pres_df[us_pres_df["height(cm)"] > ht_mode ]

order                   name  height(cm)
0       1      George Washington         189
2       3       Thomas Jefferson         189
6       7         Andrew Jackson         185
15     16        Abraham Lincoln         193
29     32  Franklin D. Roosevelt         188
33     36      Lyndon B. Johnson         193
37     40          Ronald Reagan         185
38     41      George H. W. Bush         188
39     42           Bill Clinton         188
41     44           Barack Obama         185

## Assignment on Pandas

In [299]:
import numpy as np
!pip install pandas
import pandas as pd


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip


**Q1: Create the following series. Convert the index of the series into a column of a dataframe.**

In [300]:
s = pd.Series(data=range(6),index=[chr(i) for i in range(65,65+6)])
s

A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64

In [301]:
sdf = pd.DataFrame({"index": s.index, "0":s.values})
sdf

index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4
5     F  5

**Q2: Create a dataframe to get the below data**

In [302]:
nums = np.arange(25).reshape(5,5)
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [303]:
mdf = pd.DataFrame(nums,columns=[chr(i) for i in range(97,97+5)])
mdf

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

**Replace the column `a` as below** 

`Hint:Use pd.concat()`

In [304]:
newdf = pd.DataFrame(np.identity(5),columns=[i for i in range(0,25,5)],dtype=int)
newdf

0   5   10  15  20
0   1   0   0   0   0
1   0   1   0   0   0
2   0   0   1   0   0
3   0   0   0   1   0
4   0   0   0   0   1

In [305]:
mmdf = mdf.drop('a',axis=1)
mmdf

b   c   d   e
0   1   2   3   4
1   6   7   8   9
2  11  12  13  14
3  16  17  18  19
4  21  22  23  24

In [306]:
pd.concat([newdf,mmdf],axis=1)

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

**Q3: Do vertical and horizontal stacking on the following data**

In [307]:
s1 = pd.Series(np.arange(10))
df1 = pd.DataFrame(s1)
df1

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [308]:
s2 = pd.Series([chr(i) for i in range(97,97+10)])
df2 = pd.DataFrame(s2)
df2

0
0  a
1  b
2  c
3  d
4  e
5  f
6  g
7  h
8  i
9  j

In [309]:
hdf = pd.concat([df1,df2],axis=1)
hdf.columns = [0,1]
hdf

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
5  5  f
6  6  g
7  7  h
8  8  i
9  9  j

In [310]:
vdf = pd.concat([df1,df2], axis=0)
vdf

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9
0  a
1  b
2  c
3  d
4  e
5  f
6  g
7  h
8  i
9  j

**Q4: Consider you have a series with the following valid and invalid email ids. Filter out the invalid emails from the series.**
Use this as pattern: 
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [311]:
mail_ids = pd.Series(['sree@iiits.in', 'www.google.com', 'search engine.in', 'pm@india.in', 'python@top', 'USpresident@us.com'])

In [312]:
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mail_ids[mail_ids.str.match(pattern)]

0         sree@iiits.in
3           pm@india.in
5    USpresident@us.com
dtype: object

**Q5:**

**Step 1: Read ["Cars93_miss.csv"](https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv) and import only even number of columns as a Dataframe (consider column `0` too)**

In [313]:
data_url = "https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv"
cars_df = pd.read_csv(data_url)
cars_df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

**Step 2: Get summary statistics for the Dataframe**

In [314]:
cars_df.describe()

Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

**Step 3: Check for missing values, count the missing values and replace the missing values with mean.**

In [315]:
cars_df.isnull().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [316]:
cars_df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [317]:
cars_df.dtypes

Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object

In [318]:
for col in cars_df.columns:
    if cars_df[col].dtype == "object":
        # not possible to compute mean for object data type
        cars_df[col] = cars_df[col].fillna(cars_df[col].mode()[0])
    else:
        cars_df[col] = cars_df[col].fillna(cars_df[col].mean())

In [319]:
cars_df.isnull().sum() # prove that all nan are removed

Manufacturer          0
Model                 0
Type                  0
Min.Price             0
Price                 0
Max.Price             0
MPG.city              0
MPG.highway           0
AirBags               0
DriveTrain            0
Cylinders             0
EngineSize            0
Horsepower            0
RPM                   0
Rev.per.mile          0
Man.trans.avail       0
Fuel.tank.capacity    0
Passengers            0
Length                0
Wheelbase             0
Width                 0
Turn.circle           0
Rear.seat.room        0
Luggage.room          0
Weight                0
Origin                0
Make                  0
dtype: int64

**Step 4: Create a copy of the Dataframe and to the copy Filter every 5th row from the Dataframe.**

In [320]:
copied_cars_df = cars_df.copy(deep=True)
copied_cars_df = copied_cars_df[copied_cars_df.index%5 == 0]
copied_cars_df

Manufacturer         Model     Type  Min.Price      Price  Max.Price  \
0         Acura       Integra    Small  12.900000  15.900000       18.8   
5         Buick       Century  Midsize  14.200000  15.700000       17.3   
10     Cadillac       Seville  Midsize  37.500000  40.100000       42.7   
15    Chevrolet    Lumina_APV      Van  14.700000  16.300000       18.0   
20     Chrysler       LeBaron  Compact  14.500000  15.800000       17.1   
25        Dodge       Caravan      Van  17.118605  19.000000       24.4   
30         Ford       Festiva    Small   6.900000   7.400000        7.9   
35         Ford      Aerostar      Van  14.500000  19.900000       25.3   
40        Honda       Prelude   Sporty  17.000000  19.800000       22.7   
45      Hyundai        Scoupe  Midsize   9.100000  10.000000       11.0   
50      Lincoln   Continental  Midsize  33.300000  34.300000       35.3   
55        Mazda           MPV      Van  16.600000  19.100000       21.7   
60      Mercury        Cougar  Midsize  14.900000  14.900000       14.9   
65       Nissan         Quest      Van  16.700000  19.100000       21.5   
70   Oldsmobile  Eighty-Eight    Large  19.500000  20.700000       21.9   
75      Pontiac    Grand_Prix  Midsize  15.400000  18.500000       21.6   
80       Subaru        Loyale    Small  10.500000  10.900000       11.3   
85       Toyota         Camry  Midsize  15.200000  19.616484       21.2   
90   Volkswagen       Corrado   Sporty  22.900000  23.300000       23.7   

     MPG.city  MPG.highway             AirBags DriveTrain  ... Passengers  \
0   25.000000         31.0                None      Front  ...        5.0   
5   22.000000         31.0         Driver only      Front  ...        6.0   
10  16.000000         25.0  Driver & Passenger      Front  ...        5.0   
15  18.000000         23.0                None      Front  ...        7.0   
20  23.000000         28.0  Driver & Passenger      Front  ...        6.0   
25  17.000000         21.0         Driver only        4WD  ...        7.0   
30  31.000000         33.0         Driver only      Front  ...        4.0   
35  15.000000         20.0         Driver only        4WD  ...        7.0   
40  24.000000         31.0  Driver & Passenger      Front  ...        4.0   
45  26.000000         34.0                None      Front  ...        4.0   
50  17.000000         26.0  Driver & Passenger      Front  ...        6.0   
55  18.000000         24.0                None        4WD  ...        7.0   
60  19.000000         26.0                None       Rear  ...        5.0   
65  17.000000         23.0                None      Front  ...        7.0   
70  22.404762         28.0         Driver only      Front  ...        6.0   
75  19.000000         27.0                None      Front  ...        5.0   
80  25.000000         30.0                None        4WD  ...        5.0   
85  22.000000         29.0         Driver only      Front  ...        5.0   
90  18.000000         25.0                None      Front  ...        4.0   

    Length  Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  \
0    177.0      102.0   68.0         37.0           26.5     13.986486   
5    189.0      105.0   69.0         41.0           28.0     16.000000   
10   204.0      111.0   74.0         44.0           31.0     13.986486   
15   178.0      110.0   74.0         44.0           30.5     13.986486   
20   183.0      104.0   68.0         41.0           30.5     14.000000   
25   175.0      112.0   72.0         42.0           26.5     13.986486   
30   141.0       90.0   63.0         33.0           26.0     12.000000   
35   176.0      119.0   72.0         45.0           30.0     13.986486   
40   175.0      100.0   70.0         39.0           23.5      8.000000   
45   166.0       94.0   64.0         34.0           23.5      9.000000   
50   205.0      109.0   73.0         42.0           30.0     19.000000   
55   190.0      110.0   72.0         39.0           27.5     13.986486   

**Step 5: In the original data, Group the Dataframe by using the key `Manufacturer`. Use any aggregate function.**

In [321]:
cars_df.groupby(by="Manufacturer").mean()

/tmp/ipykernel_35859/2356635150.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  cars_df.groupby(by="Manufacturer").mean()


Min.Price      Price  Max.Price   MPG.city  MPG.highway  \
Manufacturer                                                             
Acura          12.900000  15.900000  18.800000  25.000000    31.000000   
Audi           21.509302  33.400000  38.450000  19.500000    26.000000   
BMW            17.118605  30.000000  21.459091  22.000000    30.000000   
Buick          20.750000  21.625000  22.489773  19.000000    27.750000   
Cadillac       35.250000  37.400000  39.500000  16.000000    25.000000   
Chevrolet      19.650000  21.641667  23.650000  19.533730    27.083333   
Chrysler       22.000000  22.650000  23.300000  21.500000    27.000000   
Dodge          13.103101  15.700000  18.900000  22.400794    27.177656   
Eagle          12.509302  15.750000  18.850000  24.500000    30.500000   
Ford           12.437500  14.962500  17.500000  21.800595    28.125000   
Geo             9.100000  10.450000  11.750000  38.000000    43.000000   
Honda          13.066667  16.466667  19.900000  30.000000    36.000000   
Hyundai         9.325000  10.475000  11.625000  24.351190    30.750000   
Infiniti       45.400000  47.900000  21.459091  17.000000    22.000000   
Lexus          27.500000  28.000000  28.400000  18.000000    24.000000   
Lincoln        33.850000  35.200000  36.550000  17.500000    26.000000   
Mazda          16.340000  17.600000  18.860000  23.600000    31.200000   
Mercedes-Benz  36.400000  46.900000  57.450000  20.702381    27.000000   
Mercury        14.100000  14.500000  14.950000  21.000000    26.000000   
Mitsubishi     15.050000  18.200000  17.179545  23.500000    26.532967   
Nissan         14.850000  17.025000  19.175000  22.750000    28.000000   
Oldsmobile     16.550000  17.500000  18.450000  21.851190    28.250000   
Plymouth       11.400000  14.400000  17.400000  22.404762    30.000000   
Pontiac        15.063721  16.140000  19.020000  22.080952    31.000000   
Saab           20.300000  28.700000  37.100000  20.000000    26.000000   
Saturn          9.200000  19.616484  12.900000  22.404762    38.000000   
Subaru         11.366667  12.933333  14.500000  27.000000    32.333333   
Suzuki          7.300000   8.600000  21.459091  39.000000    43.000000   
Toyota         15.909302  17.629121  20.550000  24.250000    30.000000   
Volkswagen     16.450000  18.025000  19.575000  20.250000    27.250000   
Volvo          21.800000  22.700000  23.500000  21.000000    28.000000   

               EngineSize  Horsepower          RPM  Rev.per.mile  \
Manufacturer                                                       
Acura            1.800000  140.000000  6300.000000       2890.00   
Audi             2.729121  172.000000  5500.000000       2407.50   
BMW              3.500000  208.000000  5700.000000       2545.00   
Buick            3.875000  157.500000  4700.000000       1982.50   
Cadillac         4.750000  247.500000  5050.000000       2170.00   
Chevrolet        3.391667  174.000000  5100.000000       2076.25   
Chrysler         3.150000  144.000000  4900.000000       1937.50   
Dodge            2.450000  137.833333  5233.333333       2455.00   
Eagle            2.500000  118.000000  5900.000000       2242.50   
Ford             2.537500  123.125000  4950.000000       2413.75   
Geo              1.300000   72.500000  5550.000000       3502.50   
Honda            2.000000  148.000000  5766.666667       2620.00   
Hyundai          1.700000  106.250000  5762.500000       2582.50   
Infiniti         4.500000  278.000000  6000.000000       1955.00   
Lexus            3.000000  185.000000  5276.666667       2325.00   
Lincoln          4.200000  185.000000  4500.000000       1837.50   
Mazda            2.040000  151.800000  5520.000000       2332.00   
Mercedes-Benz    2.750000  173.500000  5300.000000       2322.50   
Mercury          2.700000  120.000000  4775.000000       2102.50   
Mitsubishi       2.250000  147.000000  6000.000000       2357.50   
Nissan           2.500000  141.000000  5400.000000       2168.75   
Oldsmobi

**Step 6: Set the Groupby column as Index.**

In [322]:
# the question is not clear to me

**Q6:**


**Read this Dataset ["Countries.csv"](https://gist.githubusercontent.com/aakashns/28b2e504b3350afd9bdb157893f9725c/raw/994b65665757f4f8887db1c85986a897abb23d84/countries.csv)**

In [323]:
countries_data_url= "https://gist.githubusercontent.com/aakashns/28b2e504b3350afd9bdb157893f9725c/raw/994b65665757f4f8887db1c85986a897abb23d84/countries.csv"
countries_df = pd.read_csv(countries_data_url)
countries_df

location continent  population  life_expectancy  \
0       Afghanistan      Asia  38928341.0            64.83   
1           Albania    Europe   2877800.0            78.57   
2           Algeria    Africa  43851043.0            76.88   
3           Andorra    Europe     77265.0            83.73   
4            Angola    Africa  32866268.0            61.15   
..              ...       ...         ...              ...   
205         Vietnam      Asia  97338583.0            75.40   
206  Western Sahara    Africa    597330.0            70.26   
207           Yemen      Asia  29825968.0            66.12   
208          Zambia    Africa  18383956.0            63.89   
209        Zimbabwe    Africa  14862927.0            61.49   

     hospital_beds_per_thousand  gdp_per_capita  
0                          0.50        1803.987  
1                          2.89       11803.431  
2                          1.90       13913.839  
3                           NaN             NaN  
4                           NaN        5819.495  
..                          ...             ...  
205                        2.60        6171.884  
206                         NaN             NaN  
207                        0.70        1479.147  
208                        2.00        3689.251  
209                        1.70        1899.775  

[210 rows x 6 columns]

**1: How many countries does the dataframe contain?**

In [324]:
countries_count = countries_df["location"].value_counts().sum() 
assert(countries_count == len(countries_df["location"].unique()))
assert(countries_count == len(countries_df["location"].value_counts()))
countries_count

210

**2: Retrieve a list of continents from the dataframe?**

*Hint: Use the `.unique` method of a series.*

In [325]:
countries_df["continent"].unique()

array(['Asia', 'Europe', 'Africa', 'North America', 'South America',
       'Oceania'], dtype=object)

**3: What is the total population of all the countries listed in this dataset?**

In [326]:
countries_df["population"].sum()

7757980095.0

**4: What is the overall life expectancy across in the world?**

*Hint: You'll need to take a weighted average of life expectancy using populations as weights.*

In [327]:
avg_life_expectancy = np.average(a=countries_df["life_expectancy"], weights=countries_df["population"])
avg_life_expectancy

nan

In [328]:
countries_df.isnull().sum()

location                       0
continent                      0
population                     0
life_expectancy                3
hospital_beds_per_thousand    46
gdp_per_capita                27
dtype: int64

In [329]:
countries_df["life_expectancy"].isnull().sum()

3

In [330]:
len(countries_df["life_expectancy"])

210

In [331]:
countries_df[countries_df["life_expectancy"].isnull()]


location continent  population  life_expectancy  \
81   Guernsey    Europe     67052.0              NaN   
100    Jersey    Europe    101073.0              NaN   
104    Kosovo    Europe   1932774.0              NaN   

     hospital_beds_per_thousand  gdp_per_capita  
81                          NaN             NaN  
100                         NaN             NaN  
104                         NaN        9795.834

In [332]:
countries_df.dropna(subset=["life_expectancy"],inplace=True)
countries_df[countries_df["life_expectancy"].isnull()]

Empty DataFrame
Columns: [location, continent, population, life_expectancy, hospital_beds_per_thousand, gdp_per_capita]
Index: []

In [333]:
len(countries_df["life_expectancy"])

207

In [334]:
countries_df["life_expectancy"].isnull().sum()


0

In [335]:
avg_life_expectancy = np.average(a=countries_df["life_expectancy"],weights=countries_df["population"])
avg_life_expectancy

72.74135064806133

**5: Create a dataframe containing 10 countries with the highest population.**

*Hint: Chain the `sort_values` and `head` methods.*

In [336]:
most_pop = countries_df.sort_values(["population"],ascending=False).head(10)
most_pop

location      continent    population  life_expectancy  \
41           China           Asia  1.439324e+09            76.91   
90           India           Asia  1.380004e+09            69.66   
199  United States  North America  3.310026e+08            78.86   
91       Indonesia           Asia  2.735236e+08            71.72   
145       Pakistan           Asia  2.208923e+08            67.27   
27          Brazil  South America  2.125594e+08            75.88   
141        Nigeria         Africa  2.061396e+08            54.69   
15      Bangladesh           Asia  1.646894e+08            72.59   
157         Russia         Europe  1.459345e+08            72.58   
125         Mexico  North America  1.289328e+08            75.05   

     hospital_beds_per_thousand  gdp_per_capita  
41                         4.34       15308.712  
90                         0.53        6426.674  
199                        2.77       54225.446  
91                         1.04       11188.744  
145                        0.60        5034.708  
27                         2.20       14103.452  
141                         NaN        5338.454  
15                         0.80        3523.984  
157                        8.05       24765.954  
125                        1.38       17336.469

**6: Add a new column to the Dataframe to record the overall GDP per country (product of population & per capita GDP).**


In [337]:
countries_df["overall gdp"] = countries_df["population"] * countries_df["gdp_per_capita"]
countries_df

location continent  population  life_expectancy  \
0       Afghanistan      Asia  38928341.0            64.83   
1           Albania    Europe   2877800.0            78.57   
2           Algeria    Africa  43851043.0            76.88   
3           Andorra    Europe     77265.0            83.73   
4            Angola    Africa  32866268.0            61.15   
..              ...       ...         ...              ...   
205         Vietnam      Asia  97338583.0            75.40   
206  Western Sahara    Africa    597330.0            70.26   
207           Yemen      Asia  29825968.0            66.12   
208          Zambia    Africa  18383956.0            63.89   
209        Zimbabwe    Africa  14862927.0            61.49   

     hospital_beds_per_thousand  gdp_per_capita   overall gdp  
0                          0.50        1803.987  7.022622e+10  
1                          2.89       11803.431  3.396791e+10  
2                          1.90       13913.839  6.101364e+11  
3                           NaN             NaN           NaN  
4                           NaN        5819.495  1.912651e+11  
..                          ...             ...           ...  
205                        2.60        6171.884  6.007624e+11  
206                         NaN             NaN           NaN  
207                        0.70        1479.147  4.411699e+10  
208                        2.00        3689.251  6.782303e+10  
209                        1.70        1899.775  2.823622e+10  

[207 rows x 7 columns]

**7: Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million.**

In [338]:
req_df = countries_df[countries_df["population"] > 100*1000*1000].sort_values(["gdp_per_capita"]).head()
req_df

location continent    population  life_expectancy  \
63     Ethiopia    Africa  1.149636e+08            66.60   
15   Bangladesh      Asia  1.646894e+08            72.59   
145    Pakistan      Asia  2.208923e+08            67.27   
141     Nigeria    Africa  2.061396e+08            54.69   
90        India      Asia  1.380004e+09            69.66   

     hospital_beds_per_thousand  gdp_per_capita   overall gdp  
63                         0.30        1729.927  1.988786e+11  
15                         0.80        3523.984  5.803628e+11  
145                        0.60        5034.708  1.112128e+12  
141                         NaN        5338.454  1.100467e+12  
90                         0.53        6426.674  8.868838e+12

**8: Create a data frame that counts the number countries in each continent?**

*Hint: Use `groupby`, select the `location` column and aggregate using `count`.*

In [339]:
for item in countries_df.groupby(by="continent"):
    print(type(item))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [340]:
countries_df.groupby(by="continent")["location"].count()

continent
Africa           55
Asia             47
Europe           48
North America    36
Oceania           8
South America    13
Name: location, dtype: int64

**9: Create a data frame showing the total population of each continent.**

*Hint: Use `groupby`, select the population column and aggregate using `sum`.*

In [341]:
countries_df.groupby(by="continent")["population"].sum()

continent
Africa           1.339424e+09
Asia             4.607388e+09
Europe           7.464053e+08
North America    5.912425e+08
Oceania          4.095832e+07
South America    4.304611e+08
Name: population, dtype: float64

**Now, download another dataset ["covid-countries-data.csv"](https://gist.githubusercontent.com/aakashns/b2a968a6cfd9fbbb0ff3d6bd0f26262b/raw/b115ed1dfa17f10fc88bf966236cd4d9032f1df8/covid-countries-data.csv) and read the data into another Pandas data frame.**

In [342]:
covid_countries_data_url = "https://gist.githubusercontent.com/aakashns/b2a968a6cfd9fbbb0ff3d6bd0f26262b/raw/b115ed1dfa17f10fc88bf966236cd4d9032f1df8/covid-countries-data.csv"
covid_data_df = pd.read_csv(covid_countries_data_url)
covid_data_df

location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

**10: Count the number of countries for which the `total_tests` data is missing.**

*Hint: Use the `.isna` method.*

In [343]:
missing_count  = covid_data_df["total_tests"].isnull().sum()
assert(missing_count == covid_data_df.isna()["total_tests"].sum())
missing_count


122

Let's merge the two data frames, and compute some more metrics.

**11: Merge `countries_df` with `covid_data_df` on the `location` column.**

In [344]:
combined_df = countries_df.merge(covid_data_df,on="location")
combined_df



location continent  population  life_expectancy  \
0       Afghanistan      Asia  38928341.0            64.83   
1           Albania    Europe   2877800.0            78.57   
2           Algeria    Africa  43851043.0            76.88   
3           Andorra    Europe     77265.0            83.73   
4            Angola    Africa  32866268.0            61.15   
..              ...       ...         ...              ...   
202         Vietnam      Asia  97338583.0            75.40   
203  Western Sahara    Africa    597330.0            70.26   
204           Yemen      Asia  29825968.0            66.12   
205          Zambia    Africa  18383956.0            63.89   
206        Zimbabwe    Africa  14862927.0            61.49   

     hospital_beds_per_thousand  gdp_per_capita   overall gdp  total_cases  \
0                          0.50        1803.987  7.022622e+10      38243.0   
1                          2.89       11803.431  3.396791e+10       9728.0   
2                          1.90       13913.839  6.101364e+11      45158.0   
3                           NaN             NaN           NaN       1199.0   
4                           NaN        5819.495  1.912651e+11       2729.0   
..                          ...             ...           ...          ...   
202                        2.60        6171.884  6.007624e+11       1046.0   
203                         NaN             NaN           NaN        766.0   
204                        0.70        1479.147  4.411699e+10       1976.0   
205                        2.00        3689.251  6.782303e+10      12415.0   
206                        1.70        1899.775  2.823622e+10       6638.0   

     total_deaths  total_tests  
0          1409.0          NaN  
1           296.0          NaN  
2          1525.0          NaN  
3            53.0          NaN  
4           109.0          NaN  
..            ...          ...  
202          35.0     261004.0  
203           1.0          NaN  
204         571.0          NaN  
205         292.0          NaN  
206         206.0      97272.0  

[207 rows x 10 columns]

**12: Add columns `tests_per_million`, `cases_per_million` and `deaths_per_million` into `combined_df`.**

In [345]:
million = 1000*1000
combined_df["test_per_million"] = combined_df["total_tests"]/million
combined_df["cases_per_million"] = combined_df["total_cases"]/million
combined_df["deaths_per_million"] = combined_df["total_deaths"]/million
combined_df

location continent  population  life_expectancy  \
0       Afghanistan      Asia  38928341.0            64.83   
1           Albania    Europe   2877800.0            78.57   
2           Algeria    Africa  43851043.0            76.88   
3           Andorra    Europe     77265.0            83.73   
4            Angola    Africa  32866268.0            61.15   
..              ...       ...         ...              ...   
202         Vietnam      Asia  97338583.0            75.40   
203  Western Sahara    Africa    597330.0            70.26   
204           Yemen      Asia  29825968.0            66.12   
205          Zambia    Africa  18383956.0            63.89   
206        Zimbabwe    Africa  14862927.0            61.49   

     hospital_beds_per_thousand  gdp_per_capita   overall gdp  total_cases  \
0                          0.50        1803.987  7.022622e+10      38243.0   
1                          2.89       11803.431  3.396791e+10       9728.0   
2                          1.90       13913.839  6.101364e+11      45158.0   
3                           NaN             NaN           NaN       1199.0   
4                           NaN        5819.495  1.912651e+11       2729.0   
..                          ...             ...           ...          ...   
202                        2.60        6171.884  6.007624e+11       1046.0   
203                         NaN             NaN           NaN        766.0   
204                        0.70        1479.147  4.411699e+10       1976.0   
205                        2.00        3689.251  6.782303e+10      12415.0   
206                        1.70        1899.775  2.823622e+10       6638.0   

     total_deaths  total_tests  test_per_million  cases_per_million  \
0          1409.0          NaN               NaN           0.038243   
1           296.0          NaN               NaN           0.009728   
2          1525.0          NaN               NaN           0.045158   
3            53.0          NaN               NaN           0.001199   
4           109.0          NaN               NaN           0.002729   
..            ...          ...               ...                ...   
202          35.0     261004.0          0.261004           0.001046   
203           1.0          NaN               NaN           0.000766   
204         571.0          NaN               NaN           0.001976   
205         292.0          NaN               NaN           0.012415   
206         206.0      97272.0          0.097272           0.006638   

     deaths_per_million  
0              0.001409  
1              0.000296  
2              0.001525  
3              0.000053  
4              0.000109  
..                  ...  
202            0.000035  
203            0.000001  
204            0.000571  
205            0.000292  
206            0.000206  

[207 rows x 13 columns]

**13: Create a dataframe with 10 countires that have highest number of tests per million people.**

In [346]:
combined_df.sort_values(["test_per_million"],ascending=False).head(10)

location      continent    population  life_expectancy  \
196         United States  North America  3.310026e+08            78.86   
89                  India           Asia  1.380004e+09            69.66   
154                Russia         Europe  1.459345e+08            72.58   
195        United Kingdom         Europe  6.788600e+07            81.32   
73                Germany         Europe  8.378394e+07            81.33   
190                Turkey           Asia  8.433907e+07            77.69   
194  United Arab Emirates           Asia  9.890400e+06            77.97   
174                 Spain         Europe  4.675478e+07            83.56   
10              Australia        Oceania  2.549988e+07            83.44   
35                 Canada  North America  3.774216e+07            82.43   

     hospital_beds_per_thousand  gdp_per_capita   overall gdp  total_cases  \
196                        2.77       54225.446  1.794877e+13    6114406.0   
89                         0.53        6426.674  8.868838e+12    3853406.0   
154                        8.05       24765.954  3.614206e+12    1005000.0   
195                        2.54       39753.244  2.698689e+12     338676.0   
73                         8.00       45229.245  3.789485e+12     246116.0   
190                        2.81       25129.341  2.119385e+12     273301.0   
194                        1.20       67293.483  6.655595e+11      71540.0   
174                        2.97       34272.360  1.602397e+12     479554.0   
10                         3.84       44648.710  1.138537e+12      25923.0   
35                         2.50       44017.591  1.661319e+12     129923.0   

     total_deaths  total_tests  test_per_million  cases_per_million  \
196      185744.0   83898416.0         83.898416           6.114406   
89        67376.0   44337201.0         44.337201           3.853406   
154       17414.0   37176827.0         37.176827           1.005000   
195       41514.0   13447568.0         13.447568           0.338676   
73         9321.0   11208091.0         11.208091           0.246116   
190        6462.0    7247935.0          7.247935           0.273301   
194         387.0    7177430.0          7.177430           0.071540   
174       29194.0    6416533.0          6.416533           0.479554   
10          663.0    6255797.0          6.255797           0.025923   
35         9135.0    5545473.0          5.545473           0.129923   

     deaths_per_million  
196            0.185744  
89             0.067376  
154            0.017414  
195            0.041514  
73             0.009321  
190            0.006462  
194            0.000387  
174            0.029194  
10             0.000663  
35             0.009135